//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beamable.Server.Clients
{
    using System;
    using Beamable.Platform.SDK;
    using Beamable.Server;
    
    
    /// <summary> A generated client for <see cref="Beamable.Server.MyCustomContentMicroservice"/> </summary
    public sealed class MyCustomContentMicroserviceClient : MicroserviceClient
    {
        
        public MyCustomContentMicroserviceClient(BeamContext context = null) : 
                base(context)
        {
        }
        
        /// <summary>
        /// Call the LoadCustomData method on the MyCustomContentMicroservice microservice
        /// <see cref="Beamable.Server.MyCustomContentMicroservice.LoadCustomData"/>
        /// </summary>
        public Beamable.Common.Promise<Examples.MyCustomContentMicroserviceExample.Shared.MyCustomContent.MyCustomData> LoadCustomData()
        {
            string[] serializedFields = new string[0];
            return this.Request<Examples.MyCustomContentMicroserviceExample.Shared.MyCustomContent.MyCustomData>("MyCustomContentMicroservice", "LoadCustomData", serializedFields);
        }
    }
    
    internal sealed class MicroserviceParametersMyCustomContentMicroserviceClient
    {
    }
    
    [BeamContextSystemAttribute()]
    internal static class ExtensionsForMyCustomContentMicroserviceClient
    {
        
        [Beamable.Common.Dependencies.RegisterBeamableDependenciesAttribute()]
        public static void RegisterService(Beamable.Common.Dependencies.IDependencyBuilder builder)
        {
            builder.AddScoped<MyCustomContentMicroserviceClient>();
        }
        
        public static MyCustomContentMicroserviceClient MyCustomContentMicroservice(this Beamable.Server.MicroserviceClients clients)
        {
            return clients.GetClient<MyCustomContentMicroserviceClient>();
        }
    }
}
