//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beamable.Server.Clients
{
    using System;
    using Beamable.Platform.SDK;
    using Beamable.Server;
    
    
    /// <summary> A generated client for <see cref="Beamable.Examples.Features.Microservices.MyMathMicroserviceExample.MyMathMicroservice"/> </summary
    public sealed class MyMathMicroserviceClient : MicroserviceClient
    {
        
        public MyMathMicroserviceClient(BeamContext context = null) : 
                base(context)
        {
        }
        
        /// <summary>
        /// Call the AddMyValues method on the MyMathMicroservice microservice
        /// <see cref="Beamable.Examples.Features.Microservices.MyMathMicroserviceExample.MyMathMicroservice.AddMyValues"/>
        /// </summary>
        public Beamable.Common.Promise<int> AddMyValues(int a, int b)
        {
            string serialized_a = this.SerializeArgument<int>(a);
            string serialized_b = this.SerializeArgument<int>(b);
            string[] serializedFields = new string[] {
                    serialized_a,
                    serialized_b};
            return this.Request<int>("MyMathMicroservice", "AddMyValues", serializedFields);
        }
    }
    
    internal sealed class MicroserviceParametersMyMathMicroserviceClient
    {
        
        [System.SerializableAttribute()]
        internal sealed class ParameterSystem_Int32 : MicroserviceClientDataWrapper<int>
        {
        }
    }
    
    [BeamContextSystemAttribute()]
    internal static class ExtensionsForMyMathMicroserviceClient
    {
        
        [Beamable.Common.Dependencies.RegisterBeamableDependenciesAttribute()]
        public static void RegisterService(Beamable.Common.Dependencies.IDependencyBuilder builder)
        {
            builder.AddScoped<MyMathMicroserviceClient>();
        }
        
        public static MyMathMicroserviceClient MyMathMicroservice(this Beamable.Server.MicroserviceClients clients)
        {
            return clients.GetClient<MyMathMicroserviceClient>();
        }
    }
}
