//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beamable.Server.Clients
{
    using System;
    using Beamable.Platform.SDK;
    using Beamable.Server;
    
    
    /// <summary> A generated client for <see cref="Beamable.Server.MyPlayerLevelMicroservice.MyPlayerLevelMicroservice"/> </summary
    public sealed class MyPlayerLevelMicroserviceClient : Beamable.Server.MicroserviceClient
    {
        
        /// <summary>
        /// Call the GetPlayerLevel method on the MyPlayerLevelMicroservice microservice
        /// <see cref="Beamable.Server.MyPlayerLevelMicroservice.MyPlayerLevelMicroservice.GetPlayerLevel"/>
        /// </summary>
        public Beamable.Common.Promise<int> GetPlayerLevel()
        {
            string[] serializedFields = new string[0];
            return this.Request<int>("MyPlayerLevelMicroservice", "GetPlayerLevel", serializedFields);
        }
        
        /// <summary>
        /// Call the SetPlayerLevel method on the MyPlayerLevelMicroservice microservice
        /// <see cref="Beamable.Server.MyPlayerLevelMicroservice.MyPlayerLevelMicroservice.SetPlayerLevel"/>
        /// </summary>
        public Beamable.Common.Promise<bool> SetPlayerLevel(int playerLevel)
        {
            string serialized_playerLevel = this.SerializeArgument<int>(playerLevel);
            string[] serializedFields = new string[] {
                    serialized_playerLevel};
            return this.Request<bool>("MyPlayerLevelMicroservice", "SetPlayerLevel", serializedFields);
        }
    }
}
