//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beamable.Server.Clients
{
    using System;
    using Beamable.Platform.SDK;
    using Beamable.Server;
    
    
    /// <summary> A generated client for <see cref="Beamable.Examples.Features.Microservices.MyPlayerMicroserviceExample.MyPlayerMicroservice"/> </summary
    public sealed class MyPlayerMicroserviceClient : MicroserviceClient
    {
        
        public MyPlayerMicroserviceClient(BeamContext context = null) : 
                base(context)
        {
        }
        
        /// <summary>
        /// Call the GetPlayerLevel method on the MyPlayerMicroservice microservice
        /// <see cref="Beamable.Examples.Features.Microservices.MyPlayerMicroserviceExample.MyPlayerMicroservice.GetPlayerLevel"/>
        /// </summary>
        public Beamable.Common.Promise<int> GetPlayerLevel()
        {
            string[] serializedFields = new string[0];
            return this.Request<int>("MyPlayerMicroservice", "GetPlayerLevel", serializedFields);
        }
        
        /// <summary>
        /// Call the SetPlayerLevel method on the MyPlayerMicroservice microservice
        /// <see cref="Beamable.Examples.Features.Microservices.MyPlayerMicroserviceExample.MyPlayerMicroservice.SetPlayerLevel"/>
        /// </summary>
        public Beamable.Common.Promise<bool> SetPlayerLevel(int playerLevel)
        {
            string serialized_playerLevel = this.SerializeArgument<int>(playerLevel);
            string[] serializedFields = new string[] {
                    serialized_playerLevel};
            return this.Request<bool>("MyPlayerMicroservice", "SetPlayerLevel", serializedFields);
        }
    }
    
    internal sealed class MicroserviceParametersMyPlayerMicroserviceClient
    {
        
        [System.SerializableAttribute()]
        internal sealed class ParameterSystem_Int32 : MicroserviceClientDataWrapper<int>
        {
        }
    }
    
    [BeamContextSystemAttribute()]
    internal static class ExtensionsForMyPlayerMicroserviceClient
    {
        
        [Beamable.Common.Dependencies.RegisterBeamableDependenciesAttribute()]
        public static void RegisterService(Beamable.Common.Dependencies.IDependencyBuilder builder)
        {
            builder.AddScoped<MyPlayerMicroserviceClient>();
        }
        
        public static MyPlayerMicroserviceClient MyPlayerMicroservice(this Beamable.Server.MicroserviceClients clients)
        {
            return clients.GetClient<MyPlayerMicroserviceClient>();
        }
    }
}
